### ISSUE TITLE
XUnit: Failing theories generate invalid filters

### ISSUE THREAD

**Issue by jcdickinson** [rwx-research/captain#53] opened 2023-08-01 20:40 UTC
The filter being generated when theories fail is invalid, as it contains the values in parenthesis (e.g. `MyTest(foo: "Bar", bar: 1)`).

```
2023-08-01T20:20:59.7326742Z [xUnit.net 00:00:00.24] Cmg.DataLabGateway.IntegrationTests: Exception filtering tests: Incorrect format for TestCaseFilter Missing Operator '|' or '&'. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.
```

I'll look into contributing a fix.

**Comment by kylekthompson** [comment] 2023-08-01 20:57
Hello 👋

Any chance you can share an example (mostly redacted is fine) of the XML test results that cause this error. I'm unable to reproduce with our example xunit project and this XML:

```xml
<assemblies timestamp="08/01/2023 20:51:40">
  <assembly name="/Users/kylekthompson/src/captain-examples/xunit2/bin/Debug/net6.0/xunit2.dll" run-date="2023-08-01" run-time="20:51:40" total="5" passed="3" failed="2" skipped="0" time="0.638" errors="0">
    <errors />
    <collection total="5" passed="3" failed="2" skipped="0" name="Test collection for xunit2.UnitTest1" time="0.003">
      <test name="xunit2.UnitTest1.CanAddTheory(value1: -2147483648, value2: -1, expected: 2147483647)" type="xunit2.UnitTest1" method="CanAddTheory" time="0.0022118" result="Pass">
        <traits />
      </test>
      <test name="xunit2.UnitTest1.CanAddTheory(value1: 1, value2: 2, expected: 3)" type="xunit2.UnitTest1" method="CanAddTheory" time="0.0000115" result="Pass">
        <traits />
      </test>
      <test name="xunit2.UnitTest1.CanAddTheory(value1: -4, value2: -6, expected: -9)" type="xunit2.UnitTest1" method="CanAddTheory" time="0.0009501" result="Fail">
        <failure>
          <message>Assert.Equal() Failure
Expected: -10
Actual:   -9</message>
          <stack-trace>   at xunit2.UnitTest1.CanAddTheory(Int32 value1, Int32 value2, Int32 expected) in /Users/kylekthompson/src/captain-examples/xunit2/UnitTest1.cs:line 24</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="xunit2.UnitTest1.CanAddTheory(value1: -2, value2: 2, expected: 1)" type="xunit2.UnitTest1" method="CanAddTheory" time="0.0001323" result="Fail">
        <failure>
          <message>Assert.Equal() Failure
Expected: 0
Actual:   1</message>
          <stack-trace>   at xunit2.UnitTest1.CanAddTheory(Int32 value1, Int32 value2, Int32 expected) in /Users/kylekthompson/src/captain-examples/xunit2/UnitTest1.cs:line 24</stack-trace>
        </failure>
        <traits />
      </test>
      <test name="xunit2.UnitTest1.PassingTest" type="xunit2.UnitTest1" method="PassingTest" time="0.0000598" result="Pass">
        <traits />
      </test>
    </collection>
  </assembly>
</assemblies>
```

Specifically, I'm seeing that we set filter to `xunit2.UnitTest1.CanAddTheory` in this case. It's been a second since I've looked at the `--filter` option, but IIRC you can't narrow to a specific set of inline data, so I think this is expected (though the error you're seeing certainly is not!).

**Comment by jcdickinson** [comment] 2023-08-02 14:57
It looks like it's specifically strings, most likely problems with shell escaping.

**Comment by jcdickinson** [comment] 2023-08-02 16:13
I'm actually getting this for all theories - including ones with numbers only - with .Net 7.0.306, on a fresh xunit project.

According to the documentation the parenthesis need to be escaped, but:

```
> dotnet test --filter "FullyQualifiedName=foo.UnitTest1.Test1(foo: 1, bar: 2)"
[xUnit.net 00:00:00.38] foo: Exception filtering tests: Incorrect format for TestCaseFilter Missing Operator '|' or '&'. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.
> dotnet test --filter 'FullyQualifiedName=foo.UnitTest1.Test1\(foo: 1, bar: 2\)'
No test matches the given testcase filter `FullyQualifiedName=foo.UnitTest1.Test1\(foo: 1, bar: 2\)`
> dotnet test --filter 'FullyQualifiedName=foo.UnitTest1.Test1\(foo: 1, bar: 2\)'
No test matches the given testcase filter `FullyQualifiedName=foo.UnitTest1.Test1\(foo: 1, bar: 2\)`
> dotnet test -t
The following Tests are available:
    foo.UnitTest1.Test1(foo: 1, bar: 2)
```

**Comment by kylekthompson** [comment] 2023-08-02 16:25
> with .Net 7.0.306

Ah, I wonder if .NET 7 has some testing related changes. This was written back when 6 was the current version. I'll try to repro locally.

**Comment by jcdickinson** [comment] 2023-08-02 16:37
I don't think this is really a captain issue - apart from correctly escaping parens (and quotes for the shell).

**Comment by jcdickinson** [comment] 2023-09-01 18:31
Would it be considered too much of a hack to add a config option allowing a regex to be applied to test names, thereby allowing a fix such as `[^(]*]` ?

**Comment by kylekthompson** [comment] 2023-09-01 19:06
Hey @jcdickinson, I'm so sorry this fell off my radar. We were having some issues with the build process since we haven't run it in a while and then I got distracted by other things at work.

I've just merged https://github.com/rwx-research/captain/pull/57 (we had to re-open it ourselves since GitHub Actions doesn't let branches from other repositories use secrets). I'm crafting a patch release and will follow up here once it's available.

Thanks for your patience!

**Comment by jcdickinson** [comment] 2023-09-01 19:07
No problem, it's been way off my radar as well.

**Comment by kylekthompson** [comment] 2023-09-01 19:46
Ok, I got nearly all the way through the release workflow and ran into an error. I _think_ I need one of my bosses (with repo admin permissions) to help me debug. They're out right now, so worst case I'll have to circle back Tuesday morning.

This time, I'll add an event to my calendar though and do it first thing Tuesday if I can't get it sorted earlier than that!

**Comment by kylekthompson** [comment] 2023-09-05 13:47
Good morning 👋 https://github.com/rwx-research/captain/releases/tag/v1.11.3 has been released with your fix! Thanks!

**Closed by kylekthompson** 2023-09-05 13:47 UTC
